name: 'Dynare 6.0 with MATLAB R2023b on macOS '

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  dynare_6_0_matlab_r2023b_macos:
    runs-on: macos-14
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Add console option to Dynare calls in run_all_files
        run: |
          sed -i '' -e '/^    dynare/ s/$/ console/' run_all_files.m
        shell: bash
      
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2023b
          products: Symbolic_Math_Toolbox Statistics_and_Machine_Learning_Toolbox Optimization_Toolbox Econometrics_Toolbox Parallel_Computing_Toolbox Control_System_Toolbox Global_Optimization_Toolbox
          cache: true
      
      - name: Download Dynare .pkg for macOS ARM64
        run: |
          curl -L "https://www.dynare.org/release/macos-arm64/dynare-6.0-arm64.pkg" -o "dynare-6.0-arm64.pkg"
        shell: bash
      
      - name: Install Dynare from the .pkg file (without sudo)
        run: |
          pkgutil --expand dynare-6.0-arm64.pkg Dynare-6.0-arm64
          cd Dynare-6.0-arm64/dynare-6.0-arm64.pkg/
          tar -zxvf Payload -C ../
          cd ..
          cd ..
        shell: bash
      
      - name: run_all_files
        uses: matlab-actions/run-command@v2
        with:
          command: |            
            addpath("Dynare-6.0-arm64/matlab");
            run_all_files;

      - name: Prepare log files for artifact upload
        if: always()
        run: |
          mkdir artifacts
          find . -name '*.log' -exec bash -c 'mkdir -p artifacts/$(dirname {}); cp {} artifacts/{};' \;
      
      - name: Upload log artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: log-files-dynare-6-0-matlab-r2023b-macos
          path: artifacts/