name: Dynare 5.4 with MATLAB R2023a using Docker

on:
  push:
    branches:
      - 5.x
  workflow_dispatch:

jobs:
  dynare_5_4_matlab_r2023a_docker:
    uses: ./.github/workflows/dynare-matlab-docker-common.yml
    with:
      dynare-version: "5.4"
    secrets:
      matlab-licensefile-base64: ${{ secrets.MATLAB_LICENSEFILE_BASE64 }}