name: Dynare 4.6.4 with MATLAB R2021a using Docker

on:
  push:
    branches:
      - 4.6
  workflow_dispatch:

jobs:
  dynare_4_6_4_matlab_r2021a_docker:
    uses: ./.github/workflows/dynare-matlab-docker-common.yml
    with:
      dynare-version: "4.6.4"
    secrets:
      matlab-licensefile-base64: ${{ secrets.MATLAB_LICENSEFILE_BASE64 }}